Kethsar/ytarchive

ytarchive.py
Most of the Linux Release have its env placed in `/usr/bin/env` instead of `/bin/env`
=> fix: env path

ytarchive.py
I didnt make a real test for this PR, but I've done a PoC:
```
import urllib.request
import socket
import re
orig_getaddrinfo = socket.getaddrinfo
inet_family = 0
def new_getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):
return orig_getaddrinfo(host=host, port=port, family=inet_family, type=type, proto=proto, flags=flags)
socket.getaddrinfo = new_getaddrinfo
r = urllib.request.urlopen('https://ip6.me')
print('Default: ' + re.search(r'\+3>(.*?)</', r.read().decode('utf-8')).group(1))
inet_family = socket.AF_INET
r = urllib.request.urlopen('https://ip6.me')
print('IPv4: ' + re.search(r'\+3>(.*?)</', r.read().decode('utf-8')).group(1))
inet_family = socket.AF_INET6
r = urllib.request.urlopen('https://ip6.me')
print('IPv6: ' + re.search(r'\+3>(.*?)</', …
```
=> Add ipv4/ipv6 selection support

ytarchive.py
use ansi escape sequences to clear the lines before printing log entries
should have higher performance and be more reliable than the previous approach of discarding screen contents by appending and erasing whitespace
also adds colors of course w
EDIT: this requires win10 from late 2016 or newer to work, otherwise there's a bit of garbage prefixed and suffixed to each log message
=> logging tweaks

ytarchive.py
ran into this while testing some other stuff -
if you rip and mux the same stream multiple times, you'll get stuck at `Muxing files` since FFmpeg is silently asking the yes/no question to overwrite the output file
this adds a serial number if the output file already exists
=> avoid filename collisions when merging

ytarchive.py
Once started, download continues even after Youtube finished post-processing stream (I suppose until download link expire in 6 hours), but page data doesn't contain `targetDurationSec` property anymore, which leads to exception when script tries to update it.
```
DEBUG: Found script element with player response in watch page.
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "ytarchive.py", line 1441, in download_stream
get_video_info(info)
File "ytarchive.py", line 893, in get_video_info
info.target_duration = formats[0]["targetDurationSec"]
KeyError: 'targetDurationSec'
DEBUG: audio0: …
```
=> Fix unhandled exception while trying to update info.target_duration after stream processing was finished.

util.go
This lets us inherit the useful/sane defaults of the default transport.
The most obvious benefit it inherits is supporting HTTP(S)_PROXY env variables from the http.ProxyFromEnvironment function. This lets you set http(s)/socks5 proxies for the program to use. This could be manually set on the `Proxy` field of Transport, but there's really no reason not to just clone the default transport as a base.
`TLSHandshakeTimeout` is already set to 10 seconds on the default transport so I omitted setting that, `ResponseHeaderTimeout` isn't set by default though so I kept that around.
=> Clone http.DefaultTransport rather than making our own.

main.go
Title, the default logger wasn't going through colorable so logging was broken because of the ANSI codes, shouldn't change anything for OSes other than Windows.
=> Fix colored output on Windows

Info.go, util.go
As YT only retains up to 5 days for seeking, it detects and adjusts sequence number to keep it working.
For any long enough livestreams, you'll get:
```
$ ./ytarchive -v https://www.youtube.com/watch?v=fEvM-OUbaKs best --threads 32
ytarchive 0.3.1
Selected quality: 720p (h264)
2022/05/05 03:44:06 INFO: Starting download to /home/lesmi/ytarchive-py/fEvM-OUbaKs__3833454310/Coffee Jazz Music - Chill Out Lounge Jazz Music Radio - 24_7 Live Stream - Slow Jazz-fEvM-OUbaKs.f140.ts
2022/05/05 03:44:06 INFO: Starting download to /home/lesmi/ytarchive-py/fEvM-OUbaKs__3833454310/Coffee Jazz Music - Chill Out Lounge Jazz Music Radio - 24_7 Live Stream - Slow Jazz-fEvM-OUbaKs.f136.ts
2022/05/05 03:44:06 WARNING: video: YT only retains the livestream 5 days past for seeking, starting from sequence …
```
=> seek up to 5 days, not from 0

README.md, main.go, util.go
`ytarchive` is a wonderful application that has helped me download a bunch of important livestreams. Thanks for your work!
I'm from China. Due to [the Great Firewall](https://en.wikipedia.org/wiki/Great_Firewall), the YouTube users from mainland China have to use proxies to watch or download videos. Currently, when using this application, to make it connect to YouTube, a VPN software or an proxy environment variable like `HTTPS_PROXY` is required. I think a built-in command line option would make things easier.
This pull request may resolve #35.
I generally:
- Changed `main.go` to read the `--proxy` option and pass it into `*http.Client`. Since this requires exposing an initialize function for the `client` variable in `util.go`, I changed the `DefaultClient()` function in `util.go` to …
=> Add `--proxy` option

Info.go
The share button on the app/website now likes to give URLs of the form `https://www.youtube.com/live/<ID>?feature=share`, which currently ytarchive doesn't support and returns an error. This PR just adds support for that format.
=> support URLs of the form 'www.youtube.com/live/<ID>'

main.go
Recent tag seems to have bumped version without bumping it in the source.
=> Bump version to 0.4.0 in main.go

Info.go, main.go, util.go
ffmpeg 6.1 fails to parse concatenated MP4 files with multiple ftyp atoms, so we have to remove all but the first.
Adds logic to pass the media mimetype through to the fragment downloader, previously the fragment downloader was trying to remove atoms from all fragments, including WEBM ones. This is pretty unlikely at actually cause issues unless by some freak chance the WEBM fragment has a valid MP4 atom in it, but figured I'd correct it anyways. Still falls back to removing from all fragments if the mimetype is blank for whatever reason.
I tested the mimetype detection with DASH and adaptive formats, both work fine, but I can't get raw Google video URLs to work (even on git master). Not sure if it's broken or I'm doing it wrong.
=> Fix MP4 fragment writing to work with ffmpeg 6.1

Info.go
The final, real start time isn't known until the stream actually starts. Knowing the real start time is useful for softchat.
=> Log stream start time when the stream starts.

Info.go, main.go, player_response.go, util.go
Added a couple new cli options to control how files are created:
`--file-permissions` (or `-fp`) and `--directory-permissions` (or `-dp`) to specify which mode is used to create files and directories.
`--temp-directory` (or `-td`) to specify a directory for temporary files which solves #175 for me.
=> New cli options to control file creation

player_response.go
Old client version stopped working again, updated based on latest yt-dlp version. Also added check if the response returns a non-200 status code so it gets debug logged when it fails instead of just silently skipping it.
=> Update Android client version and add status code check

Info.go
Fixes all lowercase of parsed VideoID, so created files now display the correct YouTube video ID.
Attempted writing similarly to surrounding code, which most resembles `youtu.be` parsing but using TrimPrefix with "/live/". Checked output with a stream and it kept capitalizations.
Hoping this commit and pull request works out well; haven't really done this whole process before :p
Closes #182
=> Fix "/live/VideoID" Parsing

Info.go
Livestreams that are shorts seem to have a url like `https://www.youtube.com/shorts/<ID>`, which currently give an error if you use them with `ytarchive`. This PR just adds support for these URLs.
Tested by building and running with a shorts livestream that was scheduled to start soon. Prior to the change it would error out, after the change it accepts the URL.
=> Support YouTube links with `/shorts/` as part of the URL

Info.go, README.md, go.mod, go.sum, main.go, player_response.go, util.go
Added support for the `--live-from` option.
This option allows users to specify that they want to start capturing from one of the following:
* Now
* A time in the past: e.g. 25 minutes ago
* A time in the future: e.g. Wait 30 minutes then start capturing.
---
Usage:
```
--live-from [DURATION] or [NOW]
Starts the download from the specified time duration string.
Can be a negative or positive duration or 'now'.
Supports Days (d), Hours (h), Minutes (m) and Seconds (s).
Examples: * '--live-from -1h10m' will seek backwards 1 hour and 10 minutes and then 
start downloading from that time.
* '--live-from 45m30s' will wait 45 minutes and 30 seconds from now and then
start downloading.
* '--live-from now' will start recording from the current stream timestamp.
```
---
Features: 
* Does not break …
=> Add feature --live-from

README.md, main.go, util.go
Added a flag `l` to use the same lookalike characters as yt-dlp. This allows the ytarchive output (such as livestream, description and thumbnail) and a possible accompanying yt-dlp output (such as live chat and metadata) to get saved in the same output directory when this flag is used. Useful especially when both programs are used in conjunction.
=> Option to use lookalike characters instead of underscores

Info.go
If you open YouTube on a mobile browser it'll be of the form `m.youtube.com/watch?`, which currently fails if you try to copy that link and pass it to `ytarchive`.
Tested by building a binary and testing a mobile link, which now is correctly parsed.
=> Support YouTube links copied from mobile browser
